version: "3.8"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - my-pg-data-1:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: anton
      POSTGRES_DB: anton
      POSTGRES_HOST: postgres
    restart: always
    
  pgadmin: 
    container_name: pgadmin4_container 
    image: dpage/pgadmin4 
    restart: always 
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root 
    ports: 
      - "5050:80" 